### ISSUE TITLE
Awesome stuff!

### ISSUE THREAD

**Issue by mscrivo** [RothAndrew/docker-dotnetcore-with-azure-cli#1]
hey @RothAndrew, wanted to thank you for this, it's helped me out quite a bit!  I'm wondering what modifications you had to make to the base azure-cli image?

**Comment by RothAndrew** [comment]
It's in the Dockerfile in this repo.

**Comment by RothAndrew** [comment]
Oh I see what you are saying. The base image for this image is also an image I made. I'll have to look, hopefully I have it still laying around somewhere

**Comment by RothAndrew** [comment]
https://github.com/RothAndrew/docker-azure-cli-ubuntu-latest/blob/master/dockerfile

**Comment by mscrivo** [comment]
Thanks!
